function init()
	obj1 = gameObject.new()
	obj1:setName("Player")
	obj1:setPos(-0.6,1.292,-65.1)
	obj1:setRotationQ(0.9986774,0.02353511,0.04569906,-0.001076957)
	obj1:addComponent("lua","movementrbody.lua")
	obj1:addComponent("capsulecollider","0.49","1.85","40")
	obj1:setTrigger(false)
		obj2 = gameObject.new()
		obj2:setName("PlayerFeet")
		obj2:setParent(obj1)
		obj2:setPos(0,-0.92,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:addComponent("lua","turncontrol.lua")
			obj3 = gameObject.new()
			obj3:setName("MainCam")
			obj3:setParent(obj2)
			obj3:setPos(0,1.899,0)
			obj3:setRotationQ(1,0,0,0)
			obj3:addComponent("camera")
			obj3:addComponent("raycast")
			obj3:addComponent("sound","background.wav")
			obj3:addComponent("lua","pitchcontrol.lua")
				obj4 = gameObject.new()
				obj4:setName("Flashlight")
				obj4:setParent(obj3)
				obj4:setPos(-0.224,-0.309,0.752)
				obj4:setRotationQ(0.9987355,-0.05006309,-0.0002160296,-0.004586249)
				obj4:addComponent("lua","flashlightMove.lua")
					obj5 = gameObject.new()
					obj5:setName("flashlight")
					obj5:setParent(obj4)
					obj5:setPos(0.003000349,-1.104,0.09999967)
					obj5:setRotationQ(0.9988484,-0.04797821,0,-1.164153E-10)
					obj5:addComponent("mesh","glow","flashlight/flashlight.obj","flashlight/Diffuse.dds","flashlight/Specular.dds","flashlight/Normal.dds")
					obj5:addComponent("lua","lightControl.lua")
						obj6 = gameObject.new()
						obj6:setName("Light")
						obj6:setParent(obj5)
						obj6:setPos(-0.05600005,1.126381,0.1356813)
						obj6:setRotationQ(0.9959946,0.07501064,0.04827452,0.006141699)
						obj6:addComponent("pointlight","2.76")
						obj6 = gameObject.new()
						obj6:setName("Flashlight")
						obj6:setParent(obj5)
						obj6:setPos(-0.05600005,1.126381,0.1356813)
						obj6:setRotationQ(0.9971638,0.07522002,-2.175693E-06,0.00250293)
						obj6:addComponent("spotlight","40.32")
						obj6 = gameObject.new()
						obj6:setName("FlashLight_LQ")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("button 1")
					obj5:setParent(obj4)
					obj5:setPos(-0.006563555,-1.10419,0.0984798)
					obj5:setRotationQ(0.9988899,-0.04690796,-0.0002028938,-0.004297233)
					obj5:addComponent("mesh","glow","flashlight/button.obj","flashlight/button/Diffuse.dds","flashlight/button/Specular.dds","flashlight/button/Normal.dds")
						obj6 = gameObject.new()
						obj6:setName("Button_LQ")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("fusehold")
				obj4:setParent(obj3)
				obj4:setPos(0.224,-0.305,0.794)
				obj4:setRotationQ(0.9987355,-0.05006309,-0.0002160333,-0.004586249)
				obj4:addComponent("lua","flashlightMove.lua")
					obj5 = gameObject.new()
					obj5:setName("LeftHand")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Light (1)")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("pointlight","1.75")

	obj1 = gameObject.new()
	obj1:setName("Game_Level_Layout")
	obj1:setPos(4.9884,2.520237,-80.70944)
	obj1:setRotationQ(1,0,0,0)
		obj2 = gameObject.new()
		obj2:setName("doors_interactive")
		obj2:setParent(obj1)
		obj2:setPos(-7.248401,-2.520237,11.05644)
		obj2:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Door 1")
			obj3:setParent(obj2)
			obj3:setPos(0,0,0)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (1)")
			obj3:setParent(obj2)
			obj3:setPos(4.900001,0,12.173)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (2)")
			obj3:setParent(obj2)
			obj3:setPos(4.900001,0,17.303)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (3)")
			obj3:setParent(obj2)
			obj3:setPos(4.900001,0,24.683)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (4)")
			obj3:setParent(obj2)
			obj3:setPos(4.900001,0,32.383)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (5)")
			obj3:setParent(obj2)
			obj3:setPos(-15.1,0,14.713)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (6)")
			obj3:setParent(obj2)
			obj3:setPos(-20.429,0,16.07)
			obj3:setRotationQ(0.7031578,0,0.7110339,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (7)")
			obj3:setParent(obj2)
			obj3:setPos(-20.38736,0,8.974697)
			obj3:setRotationQ(0.7031578,0,0.7110339,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (8)")
			obj3:setParent(obj2)
			obj3:setPos(-20.38,0,23.33)
			obj3:setRotationQ(0.7031578,0,0.7110339,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (15)")
			obj3:setParent(obj2)
			obj3:setPos(-9.93,0,26.82)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (16)")
			obj3:setParent(obj2)
			obj3:setPos(22.43,0,9.1)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (17)")
			obj3:setParent(obj2)
			obj3:setPos(8.78,0,9.099998)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (18)")
			obj3:setParent(obj2)
			obj3:setPos(38.83,0,15.04)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (19)")
			obj3:setParent(obj2)
			obj3:setPos(24.92,0,-2.72)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (20)")
			obj3:setParent(obj2)
			obj3:setPos(24.92,0,-11.36)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (21)")
			obj3:setParent(obj2)
			obj3:setPos(40.22,0,-11.43)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (22)")
			obj3:setParent(obj2)
			obj3:setPos(-3.087,0.007,-6.415)
			obj3:setRotationQ(0.7097912,0,0.7044121,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (23)")
			obj3:setParent(obj2)
			obj3:setPos(0.35,0,39.12)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0.015,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (24)")
			obj3:setParent(obj2)
			obj3:setPos(0.3499999,0,45.32)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (25)")
			obj3:setParent(obj2)
			obj3:setPos(0.95,0,54.91)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (27)")
			obj3:setParent(obj2)
			obj3:setPos(0.9499998,0,83.99)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (30)")
			obj3:setParent(obj2)
			obj3:setPos(12.741,0,90.727)
			obj3:setRotationQ(0.2597412,0,-0.9656783,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (32)")
			obj3:setParent(obj2)
			obj3:setPos(-13.2,0,88.775)
			obj3:setRotationQ(-0.2553386,0,-0.9668517,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (33)")
			obj3:setParent(obj2)
			obj3:setPos(-17.78,0,84.51)
			obj3:setRotationQ(-0.4968775,0,-0.8678207,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (34)")
			obj3:setParent(obj2)
			obj3:setPos(-21,0,78.94)
			obj3:setRotationQ(-0.4968775,0,-0.8678207,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (35)")
			obj3:setParent(obj2)
			obj3:setPos(20.845,0,84.596)
			obj3:setRotationQ(0.8660254,0,0.5,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (38)")
			obj3:setParent(obj2)
			obj3:setPos(16.07,0,49.82)
			obj3:setRotationQ(0.9659258,0,-0.2588191,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (39)")
			obj3:setParent(obj2)
			obj3:setPos(10.46,0,46.6)
			obj3:setRotationQ(0.9659258,0,-0.2588191,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (13)")
			obj3:setParent(obj2)
			obj3:setPos(-22.77,0,73.17)
			obj3:setRotationQ(-0.7045553,0,-0.7096492,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (41)")
			obj3:setParent(obj2)
			obj3:setPos(-11.614,0,48.817)
			obj3:setRotationQ(0.9659259,0,0.258819,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
			obj3 = gameObject.new()
			obj3:setName("Door 1 (44)")
			obj3:setParent(obj2)
			obj3:setPos(-10.23,0,77.57)
			obj3:setRotationQ(0.9037136,0,-0.4281377,0)
				obj4 = gameObject.new()
				obj4:setName("Door")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("DoorCol")
					obj5:setParent(obj4)
					obj5:setPos(0.645,1.158,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","doors/Doors_Cells/Door_Cell.obj","doors/Doors_Cells/Diffuse.dds","doors/Doors_Cells/Specular.dds","doors/Doors_Cells/Normal.dds")
					obj5:addComponent("lua","door.lua")
					obj5:addComponent("boxcollider","1.319854","2.331214","0.148174","0")
					obj5:setTrigger(false)
		obj2 = gameObject.new()
		obj2:setName("Navigation")
		obj2:setParent(obj1)
		obj2:setPos(-4.9884,-2.520237,80.70944)
		obj2:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Navigation")
			obj3:setParent(obj2)
			obj3:setPos(2.02,2.996,-7.685997)
			obj3:setRotationQ(0.7071068,0,0.7071068,0)
			obj3:addComponent("mesh","glow","static_objects/Navigation.obj","Navigation/Diffuse_Arrows.dds","Navigation/Specular.dds","Navigation/Normal.dds")
			obj3:addComponent("glowcontroller")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Navigation (1)")
			obj3:setParent(obj2)
			obj3:setPos(-1.243,2.923,-24.253)
			obj3:setRotationQ(0.5,-0.5,0.5,0.5)
			obj3:addComponent("mesh","glow","static_objects/Navigation.obj","Navigation/Diffuse_Arrows.dds","Navigation/Specular.dds","Navigation/Normal.dds")
			obj3:addComponent("glowcontroller")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Navigation (2)")
			obj3:setParent(obj2)
			obj3:setPos(0.592,2.197,-69.48)
			obj3:setRotationQ(0.5,-0.5,0.5,0.5)
			obj3:addComponent("mesh","glow","static_objects/Navigation.obj","Navigation/Diffuse_Arrows.dds","Navigation/Specular.dds","Navigation/Normal.dds")
			obj3:addComponent("glowcontroller")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Navigation (3)")
			obj3:setParent(obj2)
			obj3:setPos(-5.311,2.54,-43.859)
			obj3:setRotationQ(-1.872535E-07,0,-1,0)
			obj3:addComponent("mesh","glow","static_objects/Navigation.obj","Navigation/Diffuse_Arrows.dds","Navigation/Specular.dds","Navigation/Normal.dds")
			obj3:addComponent("glowcontroller")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Navigation (4)")
			obj3:setParent(obj2)
			obj3:setPos(22.352,0.296,-78.265)
			obj3:setRotationQ(0.6891631,-0.6842824,0.158285,-0.1782065)
			obj3:addComponent("mesh","glow","static_objects/Navigation.obj","Navigation/Diffuse_Arrows.dds","Navigation/Specular.dds","Navigation/Normal.dds")
			obj3:addComponent("glowcontroller")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
		obj2 = gameObject.new()
		obj2:setName("interactive_objects")
		obj2:setParent(obj1)
		obj2:setPos(-9.836987,-13.99527,65.49167)
		obj2:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Fuse_Box")
			obj3:setParent(obj2)
			obj3:setPos(13.1354,12.425,19.07)
			obj3:setRotationQ(0.7071068,0,-0.7071068,0)
			obj3:addComponent("mesh","specular","interactive_objects/Fusebox_and_Batteries/Fuse_Box.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Box/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Box/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Box/Normal.dds")
			obj3:addComponent("meshcollider","colliders/Fuse_Box.obj ")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Box_Colliders")
				obj4:setParent(obj3)
				obj4:setPos(-0.072,1.436,-0.013)
				obj4:setRotationQ(0.7071068,0,0.7071068,0)
					obj5 = gameObject.new()
					obj5:setName("FusePos")
					obj5:setParent(obj4)
					obj5:setPos(-0.073,0.322,0.082)
					obj5:setRotationQ(0.7071068,0,-0.7071068,0)
					obj5:addComponent("boxcollider","0.095948","0.15","0.1185948","0")
					obj5:setTrigger(false)
					obj5:addComponent("lua","fusesocket.lua")
					obj5 = gameObject.new()
					obj5:setName("FusePos")
					obj5:setParent(obj4)
					obj5:setPos(-0.073,0.321,-0.017)
					obj5:setRotationQ(0.7071068,0,-0.7071068,0)
					obj5:addComponent("boxcollider","0.095948","0.15","0.1185948","0")
					obj5:setTrigger(false)
					obj5:addComponent("lua","fusesocket.lua")
					obj5 = gameObject.new()
					obj5:setName("FusePos")
					obj5:setParent(obj4)
					obj5:setPos(-0.073,0.167,-0.02)
					obj5:setRotationQ(0.7071068,0,-0.7071068,0)
					obj5:addComponent("boxcollider","0.095948","0.15","0.1185948","0")
					obj5:setTrigger(false)
					obj5:addComponent("lua","fusesocket.lua")
					obj5 = gameObject.new()
					obj5:setName("FusePos")
					obj5:setParent(obj4)
					obj5:setPos(-0.073,0.167,0.079)
					obj5:setRotationQ(0.7071068,0,-0.7071068,0)
					obj5:addComponent("boxcollider","0.095948","0.15","0.1185948","0")
					obj5:setTrigger(false)
					obj5:addComponent("lua","fusesocket.lua")
					obj5 = gameObject.new()
					obj5:setName("FusePos")
					obj5:setParent(obj4)
					obj5:setPos(-0.073,0.001,0.082)
					obj5:setRotationQ(0.7071068,0,-0.7071068,0)
					obj5:addComponent("boxcollider","0.095948","0.15","0.1185948","0")
					obj5:setTrigger(false)
					obj5:addComponent("lua","fusesocket.lua")
					obj5 = gameObject.new()
					obj5:setName("FusePos")
					obj5:setParent(obj4)
					obj5:setPos(-0.073,0.014,-0.019)
					obj5:setRotationQ(0.7071068,0,-0.7071068,0)
					obj5:addComponent("boxcollider","0.095948","0.15","0.1185948","0")
					obj5:setTrigger(false)
					obj5:addComponent("lua","fusesocket.lua")
			obj3 = gameObject.new()
			obj3:setName("Fuse_Group")
			obj3:setParent(obj2)
			obj3:setPos(19.875,11.50244,-12.7)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse")
				obj4:setParent(obj3)
				obj4:setPos(-7.048,0.5900002,31.419)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.09","0.09","0.12","0")
				obj4:setTrigger(false)
				obj4:addComponent("lua","fuse.lua")
					obj5 = gameObject.new()
					obj5:setName("Fuse_Part_LP")
					obj5:setParent(obj4)
					obj5:setPos(0,-0.0352,-0.053)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
					obj5:addComponent("glowcontroller")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Battery_BIG (1)")
				obj4:setParent(obj3)
				obj4:setPos(-15.98425,3.5714,-30.85526)
				obj4:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4:addComponent("boxcollider","0.11","0.14","0.11","0")
				obj4:setTrigger(false)
				obj4:addComponent("lua","battery.lua")
					obj5 = gameObject.new()
					obj5:setName("Battery_LP_Big")
					obj5:setParent(obj4)
					obj5:setPos(0,-0.06939983,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big.obj","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Specular.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Normal.dds")
					obj5:addComponent("glowcontroller")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (1)")
				obj4:setParent(obj3)
				obj4:setPos(-23.175,-0.01854134,0)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (2)")
				obj4:setParent(obj3)
				obj4:setPos(0.02499962,-0.01854134,0)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (3)")
				obj4:setParent(obj3)
				obj4:setPos(-41.375,-0.01854134,-33.5)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (4)")
				obj4:setParent(obj3)
				obj4:setPos(1.325001,-0.01854134,-36.8)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (5)")
				obj4:setParent(obj3)
				obj4:setPos(-3.075001,-0.01854134,-59.60001)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (6)")
				obj4:setParent(obj3)
				obj4:setPos(-40.875,-0.01854134,-42.5)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Fuse_Part_LP (7)")
				obj4:setParent(obj3)
				obj4:setPos(24.625,-0.01854134,-42.5)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.06","0.036887","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP.obj","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Specular.dds","interactive_objects/Fusebox_and_Batteries/Fuse_Part_LP/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Battery_Group")
			obj3:setParent(obj2)
			obj3:setPos(10.37075,8.303841,-41.74526)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Battery_LP_Big (1)")
				obj4:setParent(obj3)
				obj4:setPos(-17.04,3.180799,33.47)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.05","0.08","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big.obj","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Specular.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Battery_LP_Big (2)")
				obj4:setParent(obj3)
				obj4:setPos(4.329249,3.180799,22.14526)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.05","0.08","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big.obj","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Specular.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Battery_LP_Big (3)")
				obj4:setParent(obj3)
				obj4:setPos(-22.87075,3.1808,-16.75475)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.05","0.08","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big.obj","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Specular.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Battery_LP_Big (4)")
				obj4:setParent(obj3)
				obj4:setPos(23.62925,3.180799,-5.554741)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("boxcollider","0.05","0.08","0.05220701","0")
				obj4:setTrigger(false)
				obj4:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big.obj","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Specular.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Normal.dds")
				obj4:addComponent("glowcontroller")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Battery_BIG")
				obj4:setParent(obj3)
				obj4:setPos(2.456249,3.842,59.99726)
				obj4:setRotationQ(0.7071068,0,-0.7071068,0)
				obj4:addComponent("boxcollider","0.11","0.14","0.11","1")
				obj4:setTrigger(false)
				obj4:addComponent("lua","battery.lua")
					obj5 = gameObject.new()
					obj5:setName("Battery_LP_Big")
					obj5:setParent(obj4)
					obj5:setPos(0,-0.06939983,0)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","glow","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big.obj","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Diffuse.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Specular.dds","interactive_objects/Fusebox_and_Batteries/Battery_LP_Big/Normal.dds")
					obj5:addComponent("glowcontroller")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
		obj2 = gameObject.new()
		obj2:setName("static_objects")
		obj2:setParent(obj1)
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Bathrooms")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Bathroom_Cells")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Bathroom_Cells")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.520237,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bathrooms/Bathroom_Cells/Bathroom_Cells_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Bathroom_Cells/Bathroom_Cells.obj","static_objects/Bathrooms/Bathroom_Cells/Diffuse_Walls.dds","static_objects/Bathrooms/Bathroom_Cells/Specular_Walls.dds","static_objects/Bathrooms/Bathroom_Cells/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Bathroom_Cells_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-110.2)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Bathroom_Cells/Bathroom_Cells_Props.obj","static_objects/Bathrooms/Bathroom_Cells/Diffuse_Props.dds","static_objects/Bathrooms/Bathroom_Cells/Specular_Props.dds","static_objects/Bathrooms/Bathroom_Cells/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Big_Bathroom")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Big_Bathroom")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.520237,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bathrooms/Big_Bathroom/Big_Bathroom_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Big_Bathroom/Big_Bathroom.obj","static_objects/Bathrooms/Big_Bathroom/Diffuse_Walls.dds","static_objects/Bathrooms/Big_Bathroom/Specular_Walls.dds","static_objects/Bathrooms/Big_Bathroom/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Big_Bathroom_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-116.7)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Big_Bathroom/Big_Bathroom_Props.obj","static_objects/Bathrooms/Big_Bathroom/Diffuse_Props.dds","static_objects/Bathrooms/Big_Bathroom/Specular_Props.dds","static_objects/Bathrooms/Big_Bathroom/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Medium_Bathroom_Theater")
				obj4:setParent(obj3)
				obj4:setPos(0.14,-0.42,-0.06)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Bathroom_Theater")
					obj5:setParent(obj4)
					obj5:setPos(-0.6384007,-2.100237,0.1694437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Medium_Bathroom_Theater/Medium_Bathroom_Theater.obj","static_objects/Bathrooms/Medium_Bathroom_Theater/Diffuse_Walls.dds","static_objects/Bathrooms/Medium_Bathroom_Theater/Specular_Walls.dds","static_objects/Bathrooms/Medium_Bathroom_Theater/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Bathroom_Theater_Props")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.381,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Medium_Bathroom_Theater/Medium_Bathroom_Theater_Props.obj","static_objects/Bathrooms/Medium_Bathroom_Theater/Diffuse_Props.dds","static_objects/Bathrooms/Medium_Bathroom_Theater/Specular_Props.dds","static_objects/Bathrooms/Medium_Bathroom_Theater/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Small_Bathroom")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bathroom")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.795,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bathrooms/Small_Bathroom/Small_Bathroom_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Small_Bathroom/Small_Bathroom.obj","static_objects/Bathrooms/Small_Bathroom/Diffuse_Walls.dds","static_objects/Bathrooms/Small_Bathroom/Specular_Walls.dds","static_objects/Bathrooms/Small_Bathroom/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("Small_Bathroom:Bathrooms_Small_Bathroom:Game_Layout_Rooms_Small_Bathroom:Game_Level_Part_2_Small_Bathroom:Small_Bathroom_SmallBathroom_LQ")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
						obj6 = gameObject.new()
						obj6:setName("SmallBathroom_LQ")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bathroom_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-126.5)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bathrooms/Small_Bathroom/Small_Bathroom_Props.obj","static_objects/Bathrooms/Small_Bathroom/Diffuse_Props.dds","static_objects/Bathrooms/Small_Bathroom/Specular_Props.dds","static_objects/Bathrooms/Small_Bathroom/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Floor_Collision_Box")
			obj3:setParent(obj2)
			obj3:setPos(-4.9884,-2.520237,80.70944)
			obj3:setRotationQ(1,0,0,0)
			obj3:addComponent("meshcollider","colliders/Floor_Collision_Box.obj")
			obj3:addComponent("mesh","specular","static_objects/Floor_Collision_Box.obj","white.dds","white.dds","white_n.dds")
				obj4 = gameObject.new()
				obj4:setName("default")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Bedrooms")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Common_Bedroom")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Common_Bedroom")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Common_Bedroom/Common_Bedroom_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Common_Bedroom/Common_Bedroom.obj","static_objects/Bedrooms/Common_Bedroom/Diffuse_Walls.dds","static_objects/Bedrooms/Common_Bedroom/Specular_Walls.dds","static_objects/Bedrooms/Common_Bedroom/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Common_Bedroom_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-51.9)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Common_Bedroom/Common_Bedroom_Props.obj","static_objects/Bedrooms/Common_Bedroom/Diffuse_Props.dds","static_objects/Bedrooms/Common_Bedroom/Specular_Props.dds","static_objects/Bedrooms/Common_Bedroom/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Medium_Room_1")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Room_1")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Medium_Room_1/Medium_Room_1_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Medium_Room_1/Medium_Room_1.obj","static_objects/Bedrooms/Medium_Room_1/Diffuse_Walls.dds","static_objects/Bedrooms/Medium_Room_1/Specular_Walls.dds","static_objects/Bedrooms/Medium_Room_1/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Room_1_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-47.8)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Medium_Room_1/Medium_Room_1_Props.obj","static_objects/Bedrooms/Medium_Room_1/Diffuse_Props.dds","static_objects/Bedrooms/Medium_Room_1/Specular_Props.dds","static_objects/Bedrooms/Medium_Room_1/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Medium_Room_2")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Room_2")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Medium_Room_2/Medium_Room_2_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Medium_Room_2/Medium_Room_2.obj","static_objects/Bedrooms/Medium_Room_2/Diffuse_Walls.dds","static_objects/Bedrooms/Medium_Room_2/Specular_Walls.dds","static_objects/Bedrooms/Medium_Room_2/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Room_2_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-37.3)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Medium_Room_2/Medium_Room_2_Props.obj","static_objects/Bedrooms/Medium_Room_2/Diffuse_Props.dds","static_objects/Bedrooms/Medium_Room_2/Specular_Props.dds","static_objects/Bedrooms/Medium_Room_2/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Medium_Room_3")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Room_3")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Medium_Room_3/Medium_Room_3_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Medium_Room_3/Medium_Room_3.obj","static_objects/Bedrooms/Medium_Room_3/Diffuse_Walls.dds","static_objects/Bedrooms/Medium_Room_3/Specular_Walls.dds","static_objects/Bedrooms/Medium_Room_3/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Medium_Room_3_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-42.3)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Medium_Room_3/Medium_Room_3_Props.obj","static_objects/Bedrooms/Medium_Room_3/Diffuse_Props.dds","static_objects/Bedrooms/Medium_Room_3/Specular_Props.dds","static_objects/Bedrooms/Medium_Room_3/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Small_Bedroom_1")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bedroom_1")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Small_Bedroom_1/Small_Bedroom_1_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Small_Bedroom_1/Small_Bedroom_1.obj","static_objects/Bedrooms/Small_Bedroom_1/Diffuse_Walls.dds","static_objects/Bedrooms/Small_Bedroom_1/Specular_Walls.dds","static_objects/Bedrooms/Small_Bedroom_1/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bedroom_1_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-56.3)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Small_Bedroom_1/Small_Bedroom_1_Props.obj","static_objects/Bedrooms/Small_Bedroom_1/Diffuse_Props.dds","static_objects/Bedrooms/Small_Bedroom_1/Specular_Props.dds","static_objects/Bedrooms/Small_Bedroom_1/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Small_Bedroom_2")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bedroom_2")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Small_Bedroom_2/Small_Bedroom_2_Collider.obj")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Small_Bedroom_2/Small_Bedroom_2.obj","static_objects/Bedrooms/Small_Bedroom_2/Diffuse_Walls.dds","static_objects/Bedrooms/Small_Bedroom_2/Specular_Walls.dds ","static_objects/Bedrooms/Small_Bedroom_2/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bedroom_2_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-60.2)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Small_Bedroom_2/Small_Bedroom_2_Props.obj","static_objects/Bedrooms/Small_Bedroom_2/Diffuse_Props.dds","static_objects/Bedrooms/Small_Bedroom_2/Specular_Props.dds","static_objects/Bedrooms/Small_Bedroom_2/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Small_Bedroom_3")
				obj4:setParent(obj3)
				obj4:setPos(4.49,0,-80.6)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bedroom_3")
					obj5:setParent(obj4)
					obj5:setPos(-4.9884,-2.520237,80.70944)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("meshcollider","colliders/Bedrooms/Small_Bedroom_3/Small_Bedroom_3_Collider.obj ")
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Small_Bedroom_3/Small_Bedroom_3.obj ","static_objects/Bedrooms/Small_Bedroom_3/Diffuse_Walls.dds","static_objects/Bedrooms/Small_Bedroom_3/Specular_Walls.dds","static_objects/Bedrooms/Small_Bedroom_3/Normal_Walls.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Small_Bedroom_3_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-33.4)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Bedrooms/Small_Bedroom_3/Small_Bedroom_3_Props.obj"," static_objects/Bedrooms/Small_Bedroom_3/Diffuse_Props.dds","static_objects/Bedrooms/Small_Bedroom_3/Specular_Props.dds","static_objects/Bedrooms/Small_Bedroom_3/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Cells")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Cells_Lower_Level")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Cells_Lower_Level")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.520237,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Cells/Cells_Lower_Level/Cells_Lower_Level.obj","static_objects/Cells/Cells_Lower_Level/Diffuse_Walls.dds","static_objects/Cells/Cells_Lower_Level/Specular_Walls.dds","static_objects/Cells/Cells_Lower_Level/Normal_Walls.dds")
					obj5:addComponent("meshcollider","colliders/Cells/Cells_Lower_Level/Cells_Lower_Level_Collider.obj")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Cells_Lower_Level_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,-131.1)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Cells/Cells_Lower_Level/Cells_Lower_Level_Props.obj","static_objects/Cells/Cells_Lower_Level/Diffuse_Props.dds","static_objects/Cells/Cells_Lower_Level/Specular_Props.dds ","static_objects/Cells/Cells_Lower_Level/Normal_Props.dds")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Cells_Lower_Level_Ceiling")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Cells/Cells_Lower_Level_Ceiling_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Cells/Cells_Lower_Level_Ceiling.obj","static_objects/Cells/Cells_Lower_Level_Ceiling/Diffuse_Walls.dds","static_objects/Cells/Cells_Lower_Level_Ceiling/Specular_Walls.dds","static_objects/Cells/Cells_Lower_Level_Ceiling/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Padded_Cell")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Padded_Cell")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.520237,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Cells/Padded_Cell/Padded_Cell.obj","static_objects/Cells/Padded_Cell/Diffuse_Walls.dds","static_objects/Cells/Padded_Cell/Specular_Walls.dds","static_objects/Cells/Padded_Cell/Normal_Walls.dds")
					obj5:addComponent("meshcollider","colliders/Cells/Padded_Cell_Collider.obj")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Cells_Lower_Level_Floor")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Cells/Cells_Lower_Level_Floor_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Cells/Cells_Lower_Level_Floor.obj","static_objects/Cells/Cells_Lower_Level_Floor/Diffuse_Walls.dds","static_objects/Cells/Cells_Lower_Level_Floor/Specular_Walls.dds","static_objects/Cells/Cells_Lower_Level_Floor/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Cells_Upper_Levels")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Cells/Cells_Upper_Levels.obj","static_objects/Cells/Cells_Upper_Levels/Diffuse_Walls.dds","static_objects/Cells/Cells_Upper_Levels/Specular_Walls.dds","static_objects/Cells/Cells_Upper_Levels/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Padded_Cell_2")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
					obj5 = gameObject.new()
					obj5:setName("Padded_Cell_2")
					obj5:setParent(obj4)
					obj5:setPos(-0.4984007,-2.520237,0.1094437)
					obj5:setRotationQ(1,0,0,0)
					obj5:addComponent("mesh","specular","static_objects/Cells/Padded_Cell_2/Padded_Cell_2.obj","static_objects/Cells/Padded_Cell_2/Diffuse_Walls.dds","static_objects/Cells/Padded_Cell_2/Specular_Walls.dds","static_objects/Cells/Padded_Cell_2/Normal_Walls.dds")
					obj5:addComponent("meshcollider","colliders/Cells/Padded_Cell_2_Collider.obj")
						obj6 = gameObject.new()
						obj6:setName("default")
						obj6:setParent(obj5)
						obj6:setPos(0,0,0)
						obj6:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Chapel")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Chapel")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Chapel/Chapel_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Chapel/Chapel.obj","static_objects/Chapel/Diffuse_Walls.dds","static_objects/Chapel/Specular_Walls.dds","static_objects/Chapel/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Chapel_Props (1)")
				obj4:setParent(obj3)
				obj4:setPos(0,0,-134.3)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Chapel/Chapel_Props.obj","static_objects/Chapel/Diffuse_Props.dds","static_objects/Chapel/Specular_Props.dds","static_objects/Chapel/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Hallway")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Hallway")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Hallway/Hallway_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Hallway/Hallway.obj","static_objects/Hallway/Diffuse_Walls.dds","static_objects/Hallway/Specular_Walls.dds","static_objects/Hallway/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Hallway_Props")
				obj4:setParent(obj3)
				obj4:setPos(0,0,-137.9)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Hallway/Hallway_Props.obj","static_objects/Hallway/Diffuse_Props.dds","static_objects/Hallway/Specular_Props.dds","static_objects/Hallway/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Hydrotherapy_Room")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Hydrotherapy_Room")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Hydrotherapy_Room/Hydrotherapy_Room_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Hydrotherapy_Room/Hydrotherapy_Room.obj","static_objects/Hydrotherapy_Room/Diffuse_Walls.dds","static_objects/Hydrotherapy_Room/Specular_Walls.dds","static_objects/Hydrotherapy_Room/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Hydrotherapy_Room_Props")
				obj4:setParent(obj3)
				obj4:setPos(0,0,-141.5)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Hydrotherapy_Room/Hydrotherapy_Room_Props.obj","static_objects/Hydrotherapy_Room/Diffuse_Props.dds","static_objects/Hydrotherapy_Room/Specular_Props.dds","static_objects/Hydrotherapy_Room/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Kitchen")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Kitchen")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Kitchen/Kitchen_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Kitchen/Kitchen.obj","static_objects/Kitchen/Diffuse_Walls.dds","static_objects/Kitchen/Specular_Walls.dds","static_objects/Kitchen/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Kitchen_Props")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Kitchen/Kitchen_Props.obj","static_objects/Kitchen/Diffuse_Props.dds","static_objects/Kitchen/Specular_Props.dds","static_objects/Kitchen/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("Kitchen_Props")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Living_and_Dining")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Living_and_Dining")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Living_and_Dining/Living_and_Dining.obj","static_objects/Living_and_Dining/Diffuse_Walls.dds","static_objects/Living_and_Dining/Specular_Walls.dds","static_objects/Living_and_Dining/Normal_Walls.dds")
				obj4:addComponent("meshcollider","colliders/Living_and_Dining/Living_and_Dining_Collider.obj")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Living_and_Dining_Props")
				obj4:setParent(obj3)
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Living_and_Dining/Living_and_Dining_Props.obj","static_objects/Living_and_Dining/Diffuse_Props.dds","static_objects/Living_and_Dining/Specular_Props.dds","static_objects/Living_and_Dining/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Reception")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Reception_Wall_Exit")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Reception/Reception_Wall_Exit.obj","static_objects/Reception/Diffuse_Exit.dds","static_objects/Reception/Normal_Exit.dds","static_objects/Reception/Specular_Exit.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Reception_Props")
				obj4:setParent(obj3)
				obj4:setPos(-0.51,-2.798,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Reception/Reception_Props.obj","static_objects/Reception/Diffuse_Props.dds","static_objects/Reception/Specular_Props.dds","static_objects/Reception/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("Interior_Reception_Room")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Reception")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Reception/Reception.obj","static_objects/Reception/Diffuse_Walls.dds","static_objects/Reception/Specular_Walls.dds","static_objects/Reception/Normal_Walls.dds")
				obj4:addComponent("meshcollider","colliders/Reception/Reception_Collider.obj")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Theater")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Theater")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Theater/Theater_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Theater/Theater.obj","static_objects/Theater/Diffuse_Walls.dds","static_objects/Theater/Specular_Walls.dds","static_objects/Theater/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Theater_Props")
				obj4:setParent(obj3)
				obj4:setPos(0,0,-151.2)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Theater/Theater_Props.obj","static_objects/Theater/Diffuse_Props.dds","static_objects/Theater/Specular_Props.dds","static_objects/Theater/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Torture_Room_1")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Torture_Room_1")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.520237,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Torture_Room_1/Torture_Room_1_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Torture_Room_1/Torture_Room_1.obj","static_objects/Torture_Room_1/Diffuse_Walls.dds","static_objects/Torture_Room_1/Specular_Walls.dds","static_objects/Torture_Room_1/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Torture_Room_1_Props")
				obj4:setParent(obj3)
				obj4:setPos(-0.4984007,-2.792,0.1094437)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Torture_Room_1/Torture_Room_1_Props.obj","static_objects/Torture_Room_1/Diffuse_Props.dds","static_objects/Torture_Room_1/Specular_Props.dds","static_objects/Torture_Room_1/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
			obj3 = gameObject.new()
			obj3:setName("Torture_Room_2")
			obj3:setParent(obj2)
			obj3:setPos(-4.49,0,80.6)
			obj3:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Torture_Room_2")
				obj4:setParent(obj3)
				obj4:setPos(-0.31,-2.53,0.24)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("meshcollider","colliders/Torture_Room_2/Torture_Room_2_Collider.obj")
				obj4:addComponent("mesh","specular","static_objects/Torture_Room_2/Torture_Room_2.obj","static_objects/Torture_Room_2/Diffuse_Walls.dds","static_objects/Torture_Room_2/Specular_Walls.dds","static_objects/Torture_Room_2/Normal_Walls.dds")
					obj5 = gameObject.new()
					obj5:setName("torture_room_2")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)
				obj4 = gameObject.new()
				obj4:setName("Torture_Room_2_Props")
				obj4:setParent(obj3)
				obj4:setPos(0,0,-158.9)
				obj4:setRotationQ(1,0,0,0)
				obj4:addComponent("mesh","specular","static_objects/Torture_Room_2/Torture_Room_2_Props.obj","static_objects/Torture_Room_2/Diffuse_Props.dds","static_objects/Torture_Room_2/Specular_Props.dds","static_objects/Torture_Room_2/Normal_Props.dds")
					obj5 = gameObject.new()
					obj5:setName("default")
					obj5:setParent(obj4)
					obj5:setPos(0,0,0)
					obj5:setRotationQ(1,0,0,0)

end
