function init()
print("init")
	local obj1 = gameObject.new()
	obj1:setName("13cube")
	obj1:setPos(0,1.82,5)
	obj1:setRotationQ(1,0,0,0)
	obj1:addComponent("mesh","13cube.obj","rustypaint.png","rustypaint_s.png","white_n.png")
	obj1:addComponent("lua","rotate.lua")
		local obj2 = gameObject.new()
		obj2:setName("default")
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
		
		print("init banana tesseract")

	local obj1 = gameObject.new()
	obj1:setName("Hitler")
	obj1:setPos(-1.5,0.1,1.5)
	obj1:setRotationQ(0.3,0,0.954,0)
		local obj2 = gameObject.new()
		obj2:setName("Hitler")
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
		obj2:addComponent("mesh","Hitler.obj","white.png","white.png","flat_n.png")
		
		print("init hitler ein")
		
	local obj1 = gameObject.new()
	obj1:setName("Hitler2")
	obj1:setPos(1.5,0.1,1.5)
	obj1:setRotationQ(0.3,0,-0.954,0)
		local obj2 = gameObject.new()
		obj2:setName("Hitler2")
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
		obj2:addComponent("mesh","Hitler.obj","white.png","white.png","flat_n.png")
		
		print("init hitler zwei")
		
	local objfloor = gameObject.new()
	objfloor:setName("Floor")
	objfloor:setPos(0,0,0)
	--objfloor:addComponent("lua", "raycasthit.lua")
	--objfloor:addComponent("mesh", "plane20x20_2tris_aligned_uvs.obj", "rustypaint.png","rustypaint_s.png","flat_n.png")
	objfloor:addComponent("meshcollider", "plane20x20_2tris_aligned_uvs.obj")
		
		print("init floor")
		
	local obj1 = gameObject.new()
	obj1:setName("Player")
	obj1:setPos(0,1,-5)
	--obj1:addComponent("lua","movementrbody.lua")
	obj1:addComponent("capsulecollider","0.49","1.85","0") --disabled fun
		local obj2 = gameObject.new()
		obj2:setName("PlayerFeet")
		obj2:setPos(0,-0.94,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
			local obj3 = gameObject.new()
			obj3:setName("MainCam")
			obj3:setPos(0,0.3,0)
			obj3:setRotationQ(1,0,0,0)
			obj3:setParent(obj2)
			obj3:addComponent("camera")
			--obj3:addComponent("raycast")
				local obj4 = gameObject.new()
				obj4:setName("Flashlight")
				obj4:setPos(0,0,-0.5)
				obj4:setRotationQ(1,0,0,0)
				obj4:setParent(obj3)
				obj4:addComponent("spotlight","99999999.32")
				obj4:addComponent("lua","flashlightMove.lua")
			
	--[[--
	local objpause = gameObject.new()
	objpause:setName("PauseScreen")
	objpause:setPos(-0.265,0.1,0)
	--objmenu:addComponent("mesh","plane169test.obj","MenuScreen.dds","black.dds","flat_n.png")	
	objpause:addComponent("lua", "pausecontrol.lua")
	
		local objresume = gameObject.new()
		objresume:setName("ResumeButton")
		objresume:setPos(0.01,0.7,-2)
		objresume:addComponent("mesh","ResumeGameTestSelect.obj","brown.dds","white_s.png","flat_n.png")
		objresume:addComponent("lua", "resumegamebutton.lua")
		objresume:setParent(objpause)
		objresume:setActive(false)
		
		local objsettingsp = gameObject.new()
		objsettingsp:setName("PauseSettingsButton")
		objsettingsp:setPos(-0.2,0.55,-2)	
		objsettingsp:addComponent("mesh","SettingsTest.obj","lightGray.dds","white_s.png","flat_n.png")
		objsettingsp:addComponent("lua", "settings.lua")
		objsettingsp:setParent(objpause)
		objsettingsp:setActive(false)
		
		local objexitmenu = gameObject.new()
		objexitmenu:setName("ExitToMenuButton")		
		objexitmenu:setPos(0.085,0.4,-2)	
		objexitmenu:addComponent("mesh","QuitToMenuTest.obj","lightGray.dds","white_s.png","flat_n.png")
		objexitmenu:addComponent("lua", "exittomenubutton.lua")
		objexitmenu:setParent(objpause)
		objexitmenu:setActive(false)
		
		local objexitdesk = gameObject.new()
		objexitdesk:setName("ExitToDeskButton")		
		objexitdesk:setPos(0.3,0.25,-2)	
		objexitdesk:addComponent("mesh","QuitToDesktopTest.obj","lightGray.dds","white_s.png","flat_n.png")
		objexitdesk:addComponent("lua", "exitgamebutton.lua")
		objexitdesk:setParent(objpause)
		objexitdesk:setActive(false)
	
	objpause:setActive(false)
	--]]--
	
	----
	local objmenu = gameObject.new()
	objmenu:setName("Menu")	
	objmenu:setPos(0,1,-1)	
	--objmenu:setRotationQ(0,0,-0.7,0.7)
	objmenu:addComponent("lua", "buttoncontrol.lua")
	
		local objback = gameObject.new()
		objback:setName("Background")
		objback:setPos(0,-0.09,0)	
		objback:addComponent("mesh","plane169test.obj","MenuScreen2.dds","black.dds","flat_n.png")		
		objback:setParent(objmenu)
			local objbackback = gameObject.new()
			objbackback:setName("Floor")
			objbackback:setPos(0,0,1)
			objbackback:setRotation(1,0,0,-90)
			objbackback:addComponent("mesh", "plane20x20_2tris_aligned_uvs.obj", "black.dds","black.dds","flat_n.png")
			objbackback:setParent(objback)
	
		local objtitle = gameObject.new()
		objtitle:setName("Title")
		objtitle:setPos(-0.55,0.75,-1.5)
		objtitle:setRotation(1,1,0,10)	
		objtitle:addComponent("mesh","GameTitleTest.obj","lightGray.dds","white_s.png","flat_n.png")
		objtitle:setParent(objmenu)
		
		local objplay = gameObject.new()
		objplay:setName("PlayButton")
		objplay:setPos(0.85,0.5,-1.2)	
		objplay:addComponent("mesh","StartGameTest4Select.obj","brown.dds","white_s.png","flat_n.png")
		objplay:addComponent("lua", "startgamebutton.lua")
		objplay:setParent(objmenu)
		
		local objsettings= gameObject.new()
		objsettings:setName("SettingsButton")
		objsettings:setPos(0.7,0.30,-1.2)	
		objsettings:addComponent("mesh","SettingsTest.obj","lightGray.dds","white_s.png","flat_n.png")
		objsettings:addComponent("lua", "settings.lua")
		objsettings:setParent(objmenu)
		
		local objexit = gameObject.new()
		objexit:setName("ExitButton")		
		objexit:setPos(1.2,0.10,-1.2)	
		objexit:addComponent("mesh","QuitToDesktopTest.obj","lightGray.dds","white_s.png","flat_n.png")
		objexit:addComponent("lua", "exitgamebutton.lua")
		objexit:setParent(objmenu)
	--]]--
	print("init end")
end
