function init()
	local obj1 = gameObject.new()
	obj1:setName("13cube")
	obj1:setPos(0,1.82,5)
	obj1:setRotationQ(1,0,0,0)
	obj1:addComponent("mesh","13cube.obj","rustypaint.png","rustypaint_s.png","white_n.png")
	obj1:addComponent("lua","rotate.lua")
		local obj2 = gameObject.new()
		obj2:setName("default")
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)

	local obj1 = gameObject.new()
	obj1:setName("Hitler")
	obj1:setPos(-1.5,0.1,1.5)
	obj1:setRotationQ(0.3,0,0.954,0)
		local obj2 = gameObject.new()
		obj2:setName("Hitler")
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
		obj2:addComponent("mesh","Hitler.obj","white.png","white.png","flat_n.png")
		
	local obj1 = gameObject.new()
	obj1:setName("Hitler2")
	obj1:setPos(1.5,0.1,1.5)
	obj1:setRotationQ(0.3,0,-0.954,0)
		local obj2 = gameObject.new()
		obj2:setName("Hitler2")
		obj2:setPos(0,0,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
		obj2:addComponent("mesh","Hitler.obj","white.png","white.png","flat_n.png")
		
	local objfloor = gameObject.new()
	objfloor:setName("Floor")
	objfloor:setPos(0,0,0)
	objfloor:addComponent("mesh", "plane20x20_2tris_aligned_uvs.obj", "rustypaint.png","rustypaint_s.png","flat_n.png")
	objfloor:addComponent("meshcollider", "plane20x20_2tris_aligned_uvs.obj")
	
	local obj1 = gameObject.new()
	obj1:setName("Player")
	obj1:setPos(0,1.4,-5)
	obj1:setRotationQ(0.9986774,0.02353511,0.04569906,-0.001076957)
	obj1:addComponent("lua","movementrbody.lua")
	obj1:addComponent("capsulecollider","0.46","1.97","40")
		local obj2 = gameObject.new()
		obj2:setName("PlayerFeet")
		obj2:setPos(0,-0.95,0)
		obj2:setRotationQ(1,0,0,0)
		obj2:setParent(obj1)
		obj2:addComponent("lua","turncontrol.lua")
			local obj3 = gameObject.new()
			obj3:setName("MainCam")
			obj3:setPos(0,1.7,0)
			obj3:setRotationQ(1,0,0,0)
			obj3:setParent(obj2)
			obj3:addComponent("camera")
			obj3:addComponent("lua","pitchcontrol.lua")
				local obj4 = gameObject.new()
				obj4:setName("Flashlight")
				obj4:setPos(0,0,0)
				obj4:setRotationQ(1,0,0,0)
				obj4:setParent(obj3)
				obj4:addComponent("spotlight","40000.32")
				obj4:addComponent("lua","flashlightMove.lua")				
	
	local objplane = gameObject.new()
	objplane:setName("PauseScreen")
	objplane:setPos(0,0,3)
	objplane:setRotationQ(0,0,-0.7,0.7)
	objplane:setParent(obj3)
	objplane:addComponent("mesh","plane_8192.obj","white.png","white.png","white_n.png")	
	objplane:setActive(false)
	objplane:addComponent("lua", "pausecontrol.lua")
end
